name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  find_tests:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list_files.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Find test files
        id: list_files
        run: |
          # Find all spec files, create a safe name, format as a JSON array of objects for the matrix, and set as output
          MATRIX_DATA=$(find tests -name '*.spec.ts' | while read file; do
            # Generate a safe name by replacing non-alphanumeric/underscore/dash/dot chars with underscore and removing .spec.ts
            SAFE_NAME=$(echo "$file" | sed 's/[^a-zA-Z0-9._-]/_/g' | sed 's/\.\(spec\.ts\)$//');
            # Output JSON object for each file with path and safe_name
            echo "{\"path\": \"$file\", \"safe_name\": \"$SAFE_NAME\"}";
          done | jq -s . -c)
          
          # Set the output for the matrix using a multi-line string format
          echo "matrix<<EOF" >> "$GITHUB_OUTPUT"
          # Output the JSON array wrapped in an 'include' object
          echo "{\"include\": $MATRIX_DATA}" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

  test:
    needs: [find_tests]
    timeout-minutes: 10
    strategy:
      matrix: ${{ fromJson(needs.find_tests.outputs.matrix) }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # fetch-depth: 1 # Consider shallow clone if full history isn't needed
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'  # Enable caching for faster installs

    - name: Get Playwright version
      id: playwright-version
      run: echo "PLAYWRIGHT_VERSION=$(npm ls @playwright/test --depth=0 --json | jq -r '.dependencies["@playwright/test"].version')" >> $GITHUB_OUTPUT
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        # Cache key for all browsers
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}-chromium

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium

    - name: Modify Playwright Config for Single Test
      run: |
        TEST_FILE="${{ matrix.path }}"
        # Escape forward slashes for sed regex
        ESCAPED_TEST_FILE=$(echo "$TEST_FILE" | sed 's/\//\\\//g')
        
        # Use sed to modify playwright.config.ts
        # Find the 'chromium' project and add/replace the testMatch line
        sed -i '/name: \'chromium\',/{ \n  testMatch: /'"$ESCAPED_TEST_FILE"'/, /\n}' playwright.config.ts

    - name: Run Playwright tests
      run: |
        # Generate a safe name for the output directory from the file path
        SAFE_NAME=$(echo "${{ matrix.test_file }}" | sed 's/[^a-zA-Z0-9._-]/_/g' | sed 's/\.\(spec\.ts\)$//');
        PLAYWRIGHT_OUTPUT_DIR="test-results-$SAFE_NAME"
        mkdir -p "$PLAYWRIGHT_OUTPUT_DIR"
        # Run tests using the modified config - no need to specify file path here
        npx playwright test --workers=1 --project=chromium --output="$PLAYWRIGHT_OUTPUT_DIR"
        # Optionally, generate HTML report directly into the output directory
        # npx playwright show-report "$PLAYWRIGHT_OUTPUT_DIR" --output="$PLAYWRIGHT_OUTPUT_DIR/playwright-report"

    - name: Create Combined Artifact
      if: always()
      run: |
        # Generate a safe name for the output directory
        SAFE_NAME=$(echo "${{ matrix.test_file }}" | sed 's/[^a-zA-Z0-9._-]/_/g' | sed 's/\.\(spec\.ts\)$//');
        # Create a summary file within the output directory
        echo "Test Run Summary" > test-results-$SAFE_NAME/README.md
        echo "===============" >> test-results-$SAFE_NAME/README.md
        echo "" >> test-results-$SAFE_NAME/README.md
        echo "Run ID: ${{ github.run_id }}" >> test-results-$SAFE_NAME/README.md
        echo "Branch: ${{ github.ref }}" >> test-results-$SAFE_NAME/README.md
        echo "Commit: ${{ github.sha }}" >> test-results-$SAFE_NAME/README.md
        echo "" >> test-results-$SAFE_NAME/README.md
        echo "Test Configuration:" >> test-results-$SAFE_NAME/README.md
        echo "- Browser: Chromium" >> test-results-$SAFE_NAME/README.md
        echo "- Workers: 1" >> test-results-$SAFE_NAME/README.md
        echo "- Test File: ${{ matrix.test_file }}" >> test-results-$SAFE_NAME/README.md
        echo "- Artifact Safe Name: $SAFE_NAME" >> test-results-$SAFE_NAME/README.md
        echo "" >> test-results-$SAFE_NAME/README.md
        echo "Contents:" >> test-results-$SAFE_NAME/README.md
        echo "- Playwright HTML Report: index.html (if generated in config)" >> test-results-$SAFE_NAME/README.md
        echo "- Test Results (including logs and screenshots): Contents of this directory" >> test-results-$SAFE_NAME/README.md

    - name: Generate safe artifact name
      id: generate_safe_name
      run: |
        # Generate a safe name for the artifact name and path
        SAFE_NAME=$(echo "${{ matrix.test_file }}" | sed 's/[^a-zA-Z0-9._-]/_/g' | sed 's/\.\(spec\.ts\)$//');
        echo "safe_name=$SAFE_NAME" >> "$GITHUB_OUTPUT"

    - name: Upload Combined Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ steps.generate_safe_name.outputs.safe_name }}-${{ github.run_id }}
        path: test-results-${{ steps.generate_safe_name.outputs.safe_name }}/
        retention-days: 7