name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 10
    strategy:
      matrix:
        # Define all combinations for home tests
        include:
          # Home tests run in all browsers
          - test_suite: home-modal
            browser: chromium
            workers: 3
            test_file: 01-modal.spec.ts
          - test_suite: home-modal
            browser: firefox
            workers: 3
            test_file: 01-modal.spec.ts
          - test_suite: home-modal
            browser: webkit
            workers: 3
            test_file: 01-modal.spec.ts
          - test_suite: home-navigation
            browser: chromium
            workers: 3
            test_file: 00-navigation.spec.ts
          - test_suite: home-navigation
            browser: firefox
            workers: 3
            test_file: 00-navigation.spec.ts
          - test_suite: home-navigation
            browser: webkit
            workers: 3
            test_file: 00-navigation.spec.ts
          - test_suite: home-url
            browser: chromium
            workers: 3
            test_file: 03-url-validation.spec.ts
          - test_suite: home-url
            browser: firefox
            workers: 3
            test_file: 03-url-validation.spec.ts
          - test_suite: home-url
            browser: webkit
            workers: 3
            test_file: 03-url-validation.spec.ts
          - test_suite: home-form
            browser: chromium
            workers: 3
            test_file: 02-form.spec.ts
          - test_suite: home-form
            browser: firefox
            workers: 3
            test_file: 02-form.spec.ts
          - test_suite: home-form
            browser: webkit
            workers: 3
            test_file: 02-form.spec.ts
          # Other tests run only in chromium
          - test_suite: other
            browser: chromium
            workers: 1
            test_file: ""
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # fetch-depth: 1 # Consider shallow clone if full history isn't needed
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'  # Enable caching for faster installs

    - name: Get Playwright version
      id: playwright-version
      run: echo "PLAYWRIGHT_VERSION=$(npm ls @playwright/test --depth=0 --json | jq -r '.dependencies["@playwright/test"].version')" >> $GITHUB_OUTPUT
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        # Cache key for all browsers
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}-${{ matrix.browser }}

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps ${{ matrix.browser }}

    - name: Run Playwright tests
      run: |
        if [[ "${{ matrix.test_suite }}" == home-* ]]; then
          # Run specific home test file
          npx playwright test tests/home/${{ matrix.test_file }} --workers=${{ matrix.workers }} --project=${{ matrix.browser }}
        else
          # Run all other tests in chromium
          npx playwright test --workers=${{ matrix.workers }} --project=chromium --grep-invert "Signup Links Verification"
        fi

    - name: Upload Playwright Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-${{ matrix.browser }}-${{ matrix.test_suite }}-${{ github.run_id }}
        path: playwright-report/
        retention-days: 7

    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: browser-console-logs-${{ matrix.browser }}-${{ matrix.test_suite }}-${{ github.run_id }}
        path: browser-console-logs/
        retention-days: 7
        if-no-files-found: warn

    - name: Upload Test Screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-screenshots-${{ matrix.browser }}-${{ matrix.test_suite }}-${{ github.run_id }}
        path: "*.png"
        retention-days: 7
        if-no-files-found: warn

    - name: Create Combined Artifact
      if: always()
      run: |
        # Create a directory for combined artifacts
        mkdir -p combined-artifacts
        
        # Copy all artifacts into the combined directory
        cp -r playwright-report/* combined-artifacts/ || true
        cp -r browser-console-logs/* combined-artifacts/ || true
        cp *.png combined-artifacts/ || true
        
        # Create a summary file
        echo "Test Run Summary" > combined-artifacts/README.md
        echo "===============" >> combined-artifacts/README.md
        echo "" >> combined-artifacts/README.md
        echo "Run ID: ${{ github.run_id }}" >> combined-artifacts/README.md
        echo "Branch: ${{ github.ref }}" >> combined-artifacts/README.md
        echo "Commit: ${{ github.sha }}" >> combined-artifacts/README.md
        echo "" >> combined-artifacts/README.md
        echo "Test Configuration:" >> combined-artifacts/README.md
        echo "- Browser: ${{ matrix.browser }}" >> combined-artifacts/README.md
        echo "- Test Suite: ${{ matrix.test_suite }}" >> combined-artifacts/README.md
        echo "- Workers: ${{ matrix.workers }}" >> combined-artifacts/README.md
        if [[ "${{ matrix.test_suite }}" == home-* ]]; then
          echo "- Test File: ${{ matrix.test_file }}" >> combined-artifacts/README.md
        fi
        echo "" >> combined-artifacts/README.md
        echo "Contents:" >> combined-artifacts/README.md
        echo "- Playwright HTML Report: index.html" >> combined-artifacts/README.md
        echo "- Test Logs: browser-console-logs/*.json" >> combined-artifacts/README.md
        echo "- Test Screenshots: *.png" >> combined-artifacts/README.md

    - name: Upload Combined Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.browser }}-${{ matrix.test_suite }}-${{ github.run_id }}
        path: combined-artifacts/
        retention-days: 7