name: Playwright Tests & PR on Failure

on:
  push:
    branches: [ main ] # Or your primary branch name
  pull_request:
    branches: [ main ] # Or your primary branch name

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for better PR creation

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x' # Specify your Node.js version

    - name: Install dependencies
      run: npm ci # 'npm ci' is generally recommended for CI for faster, more reliable builds

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      id: run_tests
      run: npx playwright test --workers=4
      continue-on-error: true # Important: Allows workflow to continue to create PR

    - name: Upload Playwright Report and Traces
      uses: actions/upload-artifact@v4
      if: always() # Upload artifacts even if the previous step failed
      with:
        name: playwright-results-${{ github.run_id }}
        path: |
          playwright-report/
          test-results/
          trace.zip

    - name: Create Pull Request on Failure
      if: steps.run_tests.outcome == 'failure'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.PLAYWRIGHT_PAT }}  # Use a PAT with appropriate permissions
        commit-message: "fix: Automated PR for failing Playwright tests"
        branch: "fix/failing-tests-${{ github.run_id }}" # Creates a unique branch for the fix
        base: ${{ github.ref_name }} # Creates PR against the branch the push was made to
        title: "🚨 Automated PR: Fix failing Playwright tests"
        body: |
          ## Playwright Test Failures Detected

          Tests failed on commit `${{ github.sha }}` in the `${{ github.ref_name }}` branch.
          
          ### Test Results
          - [View Test Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          - [Download Test Artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)

          ### Common Issues
          - Test timeouts
          - Navigation failures
          - Performance metric collection issues

          ### Next Steps
          1. Review the test report
          2. Check the test artifacts for detailed traces
          3. Address any failing tests
          4. Update test timeouts if needed

          This PR was automatically created to help track and fix the test failures.
        labels: bug, automated-pr, playwright-failure
        assignees: ${{ github.actor }} # Assigns the PR to the person who pushed
        delete-branch: true  # Delete the branch after PR is merged
        push-to-fork: ''  # Empty string means push to the same repository
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        committer: GitHub <noreply@github.com>
        signoff: true