name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  find_tests:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.list_files.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Find test files
        id: list_files
        run: |
          # Find all spec files, create a safe name, format as a JSON array of objects for the matrix, and set as output
          MATRIX_DATA=$(find tests -name '*.spec.ts' | while read file; do
            # Generate a safe name by replacing non-alphanumeric/underscore/dash/dot chars with underscore and removing .spec.ts
            SAFE_NAME=$(echo "$file" | sed 's/[^a-zA-Z0-9._-]/_/g' | sed 's/\.\(spec\.ts\)$//');
            # Output JSON object for each file with path and safe_name
            echo "{\"path\": \"$file\", \"safe_name\": \"$SAFE_NAME\"}";
          done | jq -s . -c)
          
          # Set the output for the matrix using a multi-line string format
          echo "matrix<<EOF" >> "$GITHUB_OUTPUT"
          # Output the JSON array wrapped in an 'include' object
          echo "{\"include\": $MATRIX_DATA}" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

  test:
    needs: [find_tests]
    timeout-minutes: 10
    strategy:
      matrix: ${{ fromJson(needs.find_tests.outputs.matrix) }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # fetch-depth: 1 # Consider shallow clone if full history isn't needed
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'  # Enable caching for faster installs

    - name: Get Playwright version
      id: playwright-version
      run: echo "PLAYWRIGHT_VERSION=$(npm ls @playwright/test --depth=0 --json | jq -r '.dependencies["@playwright/test"].version')" >> $GITHUB_OUTPUT
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        # Cache key for all browsers
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}-chromium

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium

    - name: Generate Temporary Playwright Config
      run: |
        TEMP_DIR="./temp_playwright_config"
        mkdir -p "$TEMP_DIR"
        CONFIG_FILE="$TEMP_DIR/playwright.config.js"

        # Escape the test file path for use in regex
        TEST_FILE="${{ matrix.path }}"
        # Escape backslashes, forward slashes, and dots for regex
        ESCAPED_TEST_FILE=$(echo "$TEST_FILE" | sed 's/\\/\\\\/g; s/\//\\\//g; s/\./\\./g')

        echo "// Temporary Playwright config for single test" > "$CONFIG_FILE"
        echo "const { defineConfig, devices } = require('@playwright/test');" >> "$CONFIG_FILE"
        echo "" >> "$CONFIG_FILE"
        echo "module.exports = defineConfig({" >> "$CONFIG_FILE"
        echo "  testDir: '., // Look for tests in the current directory (where the command is run)" >> "$CONFIG_FILE"
        echo "  fullyParallel: true," >> "$CONFIG_FILE"
        echo "  forbidOnly: !!process.env.CI," >> "$CONFIG_FILE"
        echo "  retries: process.env.CI ? 2 : 0," >> "$CONFIG_FILE"
        echo "  workers: 1, // Use 1 worker per job" >> "$CONFIG_FILE"
        echo "  reporter: 'html'," >> "$CONFIG_FILE"
        echo "  use: {" >> "$CONFIG_FILE"
        echo "    trace: 'on-first-retry'," >> "$CONFIG_FILE"
        echo "    ...devices['Desktop Chrome']," >> "$CONFIG_FILE"
        echo "  }," >> "$CONFIG_FILE"
        echo "  projects: [{" >> "$CONFIG_FILE"
        echo "    name: 'chromium'," >> "$CONFIG_FILE"
        echo "    testMatch: /$ESCAPED_TEST_FILE/," >> "$CONFIG_FILE"
        echo "  }]" >> "$CONFIG_FILE"
        echo "});" >> "$CONFIG_FILE"
        
        echo "Generated config file: $(cat $CONFIG_FILE)" # For debugging

    - name: Run Playwright tests
      run: |
        # Generate a safe name for the output directory from the file path
        SAFE_NAME="${{ matrix.safe_name }}"
        export SAFE_NAME # Export the variable
        PLAYWRIGHT_OUTPUT_DIR="test-results-$SAFE_NAME"
        mkdir -p "$PLAYWRIGHT_OUTPUT_DIR"
        # Run tests using the temporary config file for the specific test
        npx playwright test --config ./temp_playwright_config/playwright.config.js --workers=1 --project=chromium --output="$PLAYWRIGHT_OUTPUT_DIR"
        # Optionally, generate HTML report directly into the output directory
        # npx playwright show-report "$PLAYWRIGHT_OUTPUT_DIR" --output="$PLAYWRIGHT_OUTPUT_DIR/playwright-report"

    - name: Create Combined Artifact
      if: always()
      run: |
        # Use the safe name provided by the matrix
        SAFE_NAME="${{ matrix.safe_name }}"
        export SAFE_NAME # Export the variable
        # Ensure the output directory exists before writing the README
        PLAYWRIGHT_OUTPUT_DIR="test-results-$SAFE_NAME"
        mkdir -p "$PLAYWRIGHT_OUTPUT_DIR"
        # Create a summary file within the output directory
        touch "$PLAYWRIGHT_OUTPUT_DIR/README.md"
        
        printf "%s\n" \
          "Test Run Summary" \
          "===============" \
          "" \
          "Run ID: ${{ github.run_id }}" \
          "Branch: ${{ github.ref }}" \
          "Commit: ${{ github.sha }}" \
          "" \
          "Test Configuration:" \
          "- Browser: Chromium" \
          "- Workers: 1" \
          "- Test File: ${{ matrix.path }}" \
          "- Artifact Safe Name: $SAFE_NAME" \
          "" \
          "Contents:" \
          "- Playwright HTML Report: index.html (if generated in config)" \
          "- Test Results (including logs and screenshots): Contents of this directory" > "$PLAYWRIGHT_OUTPUT_DIR/README.md"

    - name: Generate safe artifact name
      id: generate_safe_name
      run: |
        # Use the safe name provided by the matrix
        SAFE_NAME="${{ matrix.safe_name }}"
        export SAFE_NAME # Export the variable
        echo "safe_name=$SAFE_NAME" >> "$GITHUB_OUTPUT"

    - name: Upload Combined Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.safe_name }}-${{ github.run_id }}
        path: test-results-${{ matrix.safe_name }}/
        retention-days: 7