name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # fetch-depth: 1 # Consider shallow clone if full history isn't needed
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'  # Enable caching for faster installs

    - name: Get Playwright version
      id: playwright-version
      run: echo "PLAYWRIGHT_VERSION=$(npm ls @playwright/test --depth=0 --json | jq -r '.dependencies["@playwright/test"].version')" >> $GITHUB_OUTPUT
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        # Cache key specific to OS, Playwright version, and Chromium
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.PLAYWRIGHT_VERSION }}-chromium

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      # Install only Chromium browsers for faster setup
      run: npx playwright install --with-deps chromium

    - name: Run Playwright tests
      # Run tests only for the chromium project
      run: npx playwright test --workers=1 --project=chromium

    - name: Upload Playwright Report (chromium)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-chromium-${{ github.run_id }}
        path: playwright-report/
        retention-days: 7  # Keep reports for 7 days

    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs-chromium-${{ github.run_id }}
        path: test-logs/
        retention-days: 7
        if-no-files-found: warn  # Warn if no logs are found

    - name: Upload Error Screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: error-screenshots-chromium-${{ github.run_id }}
        path: error-*.png
        retention-days: 7
        if-no-files-found: warn  # Warn if no screenshots are found

    - name: Create Combined Artifact
      if: always()
      run: |
        # Create a directory for combined artifacts
        mkdir -p combined-artifacts
        
        # Copy all artifacts into the combined directory
        cp -r playwright-report/* combined-artifacts/ || true
        cp -r test-logs/* combined-artifacts/ || true
        cp error-*.png combined-artifacts/ || true
        
        # Create a summary file
        echo "Test Run Summary" > combined-artifacts/README.md
        echo "===============" >> combined-artifacts/README.md
        echo "" >> combined-artifacts/README.md
        echo "Run ID: ${{ github.run_id }}" >> combined-artifacts/README.md
        echo "Branch: ${{ github.ref }}" >> combined-artifacts/README.md
        echo "Commit: ${{ github.sha }}" >> combined-artifacts/README.md
        echo "" >> combined-artifacts/README.md
        echo "Contents:" >> combined-artifacts/README.md
        echo "- Playwright HTML Report: index.html" >> combined-artifacts/README.md
        echo "- Test Logs: test-logs/*.json" >> combined-artifacts/README.md
        echo "- Error Screenshots: error-*.png" >> combined-artifacts/README.md

    - name: Upload Combined Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-chromium-${{ github.run_id }}
        path: combined-artifacts/
        retention-days: 7